#debug or release
; RUN_MODE = debug
RUN_MODE = debug
; RUN_MODE = test
 ELECTRON_MODE = false

[app]
PAGE_SIZE = 10
JWT_SECRET = 23347$040412

[server]
; HTTP_PORT = 5600
READ_TIMEOUT = 60
WRITE_TIMEOUT = 60

[olt]
OLT1 = "192.168.1.1/root/Netconf$150"
